### ISSUE TITLE
景点编辑 图片删除报错

### ISSUE THREAD

**Issue by chenzhigao** [yunzhiclub/beautifulArtical#765]
![qq 20180307105004](https://user-images.githubusercontent.com/29062075/37071707-c31efae2-21f8-11e8-828d-b24d0005c9c4.png)

**Comment by chenzhigao** [comment]
没有看懂那段js代码，求大家解决

**Comment by teacherpan** [comment]
@poshichao 关注下此问题。找找原因。

**Comment by poshichao** [comment]
![image](https://user-images.githubusercontent.com/28888576/37077622-ac254fe4-2216-11e8-9b74-468f00d801d0.png)
问题已找到，这里获取的是路径的域名，本地获取的是localhost，服务器获取的是beautifulartical.yunzhiclub.com，然后拼接路径的时候，本地直接用域名拼接不行，远程是没问题的

**Comment by teacherpan** [comment]
本地获取出问题的原因呢？我感觉本地也是可以拼接有效的。还是说，在删除过程中，去找了服务器的图片。然后由于在本机测试，本机上并没有图片，所以在删除的时候报错了。

**Comment by poshichao** [comment]
![image](https://user-images.githubusercontent.com/28888576/37078007-69e09c4a-2218-11e8-8c0c-4320578f53dd.png)
本地拼接路径就要把红框中localhost后那部分都加上才能删除成功。

**Comment by poshichao** [comment]
![image](https://user-images.githubusercontent.com/28888576/37078164-13cf9e72-2219-11e8-825c-473f95f6de09.png)
服务器上域名后直接就是index文件

**Comment by teacherpan** [comment]
那就说明 
![image](https://user-images.githubusercontent.com/12424383/37078326-c172691a-2219-11e8-9a1d-7a36d3bbc966.png) 
这行语句兼容性差。。。
应该在C层获取到public/index.php所在的路径，传后传给V层。
并在V层的JS代码中使用:
```
// 获取index.php所在路径
// 传给V层
$this->assign('host', $host);
```

```
var host = {$host};
```

**Comment by poshichao** [comment]
好，我改一下
