### ISSUE TITLE
将分享页面的日程部分中，蓝色条部分改为半透明状态。

### ISSUE THREAD

**Issue by CYYShirley** [yunzhiclub/beautifulArtical#769]
![image](https://user-images.githubusercontent.com/23068558/37127770-3282c7b0-22b2-11e8-8e81-248e5b6ba743.png)
如上图“伦敦”字样处的蓝色条。

**Comment by teacherpan** [comment]
@zhangxishuo 我记得这个已经更改成功了。看看，如果是的话，把这个关闭了

**Comment by imsudo** [comment]
![image](https://user-images.githubusercontent.com/28392885/37194284-708269c0-23a8-11e8-8130-7a253ac12c43.png)
我更新之后显示的是这种状态。

**Comment by teacherpan** [comment]
得加个带颜色的背景图片，才能看出来是不是透明了吧。

**Comment by imsudo** [comment]
可能是哪里改错了，我本地日程一栏目前无法上传图片。
