### ISSUE TITLE
文章编辑页计算总价，参考预览页计算总价的jQuery代码(功能类似，但不完全一样)

### ISSUE THREAD

**Issue by imsudo** [yunzhiclub/beautifulArtical#782]
![image](https://user-images.githubusercontent.com/28392885/37194318-97e5c3b8-23a8-11e8-9d49-855358873fb1.png)
![image](https://user-images.githubusercontent.com/28392885/37194405-0aaf902c-23a9-11e8-8827-2012bd205615.png)

**Comment by teacherpan** [comment]
这个用angularjs会不简单点？

**Comment by imsudo** [comment]
应该会简单一些，现在提的新需求大都要用JavaScript实现，现在只能用jQuery实现新功能。

**Comment by teacherpan** [comment]
直接在总和那块输出 {{total}}。然后每行价格信息都是一个对象。
对象的属性为：
名称 成人价 儿童价 备注

再然后，对价格信息组成的对象数组进行foreach
取出成人价的总和，儿童价的总和。
再分别 乘以 成人数 儿童数，求总和

最后：对 对象组成的这个数组进行监视。只要发现它变了，就重新算一遍总和。

**Comment by teacherpan** [comment]
angulajs与javascript jquery没有冲突 。我简单实现上，你参考参考。

**Comment by imsudo** [comment]
好的
